### ISSUE TITLE
5-3 Adding Wind

### ISSUE THREAD

**Issue by grhyne** [grhyne/SWWA_Pressure#4]
When adding wind to the grl graph (5-3-wind-graph_create), I have hit this error regarding NA values only for tags CB596, CB599, and CB616:
```{r}
> # Add wind
> grl <- graph_add_wind(grl,
+   pressure = pam$pressure,
+   filename = paste0("data/5_wind_graph/", gdl, "/", gdl, "_"),
+   thr_as = gpr$thr_as
+ )
[==========================                        ] 363925 / 696923 | sta = 2/10Error in ncdf4::ncvar_get(nc, "u", start = c(id_lon[1], id_lat[1], id_pres,  : 
  Error, passed a 'start' argument that has NA values: NA NA 2 1
```

I tried adding on an na.omit() to the graph_add_wind() function, but that did not seem to change anything. Which id_lon[1] and id_lat[1] is the error referring to in grl?

**Comment by Rafnuss** [comment]
Is the repo up to date? Can a use the data there to reproduce the issue?

**Comment by grhyne** [comment]
Yes I just committed all my recent updates, go ahead and try

**Comment by Rafnuss** [comment]
Hi @grhyne ,
I managed to track down this error. This is due to an error in labeling with a flight of a single timestep. Have you performed all checks suggested in `1-pressure.R`? One of them should have pick up on this. 
You can see that it has three flights (CB616), one with no duration.
```
> metadata(static_prob[[2]])
$sta_id
[1] 2

$nb_sample
[1] 13

$max_sample
[1] 300

$temporal_extent
[1] "2021-10-17 11:12:05 UTC" "2021-10-17 23:12:05 UTC"

$margin
[1] 30

$flight
$flight$start
[1] "2021-10-17 23:42:05 UTC" "2021-10-18 08:42:05 UTC" "2021-10-18 11:12:05 UTC"

$flight$end
[1] "2021-10-18 06:42:05 UTC" "2021-10-18 08:42:05 UTC" "2021-10-18 11:42:05 UTC"

$flight$sta_id
[1] 2 3 4
```
This is the currently label file and you can see the 1hours flight.
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/7571260/188763172-24212f66-209f-47be-8917-fccbf6d1c0ed.png">

Here would be my suggestion for this file: 
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/7571260/188763260-9e5e8027-478a-4a8b-b3e1-3ee0cbf7686d.png">

**Comment by grhyne** [comment]
Thank you for finding this! Ok I see, I think I was going conservative on labelling flights based on pressure spikes, and assumed those individual labels were short (~20-30 min) flight, which would only be detected by one point. I understand how you would label them, and it worked smoothly. It should have been picked up by the tests in 1-pressure, but I believe I had left the debug <- FALSE from the previous tag and thus did not detect the mislabelling.
