### ISSUE TITLE
Geopressureviz without light_prob

### ISSUE THREAD

**Issue by grhyne** [grhyne/SWWA_Pressure#5]
I am wanting to edit some locations / stationary duration in geopressureviz (3-static), but am not using light data due to its poor quality, or in the case of CB606 and CB609, a complete absence of light data due to tag malfunction. When I try to run the shiny app to do this, I receive the following error:

```{r}
> #Geopressureviz 
> geopressureviz <- list(
+   pam = pam,
+   static_prob = static_prob,
+   pressure_prob = pressure_prob,
+   #light_prob = light_prob,
+   pressure_timeserie = static_timeserie
+ )
> save(geopressureviz, file = paste0("data/3_static/", gpr$gdl_id, "geopressureviz.RData"))
> shiny::runApp(system.file("geopressureviz", package = "GeoPressureR"), launch.browser = getOption("browser"))
Error: "pam_data" %in% names(geopressureviz) is not TRUE
```

I was assuming these names are not TRUE is because I have negated light_prob values. I have tried setting light_prob = pressure_prob, but it does not accept that either. Since it would be painful to try and replicate a blank light_prob.Rdata files, are there any ways around this?

**Comment by Rafnuss** [comment]
This is due to an error in labeling. Have you performed all checks suggested in `1-pressure.R`?
You can see that it has three flights, one with no duration.
```
> metadata(static_prob[[2]])
$sta_id
[1] 2

$nb_sample
[1] 13

$max_sample
[1] 300

$temporal_extent
[1] "2021-10-17 11:12:05 UTC" "2021-10-17 23:12:05 UTC"

$margin
[1] 30

$flight
$flight$start
[1] "2021-10-17 23:42:05 UTC" "2021-10-18 08:42:05 UTC" "2021-10-18 11:12:05 UTC"

$flight$end
[1] "2021-10-18 06:42:05 UTC" "2021-10-18 08:42:05 UTC" "2021-10-18 11:42:05 UTC"

$flight$sta_id
[1] 2 3 4
```
This is the currently label file and you can see the 1hours flight.
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/7571260/188763172-24212f66-209f-47be-8917-fccbf6d1c0ed.png">

Here would be my suggestion for this file: 
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/7571260/188763260-9e5e8027-478a-4a8b-b3e1-3ee0cbf7686d.png">

**Comment by Rafnuss** [comment]
Ah, easy one, it should be:
```
  geopressureviz <- list(
    **pam_data** = pam,
    static_prob = static_prob,
    pressure_prob = pressure_prob,
    # light_prob = light_prob,
    pressure_timeserie = static_timeserie
  )
  save(geopressureviz, file = "~/geopressureviz.RData")
```

**Comment by grhyne** [comment]
Ah, easy! Thanks
