### ISSUE TITLE
aggregate() error in geopressureviz

### ISSUE THREAD

**Issue by grhyne** [grhyne/SWWA_Pressure#8]
When trying to run geopressureviz for the final checks in 3-static, I run into this error that seems to be related to the shiny app:
```{r}
Error in h(simpleError(msg, call)) : 
error in evaluating the argument 'x' in selecting a method for function 'aggregate': invalid argument type
```
When I view the traceback, I get:
```{r}
12.
h(simpleError(msg, call))
11.
.handleSimpleError(function (cond) 
.Internal(C_tryCatchHelper(addr, 1L, cond)), "invalid argument type", 
base::quote(!pressure$outlier))
10.
aggregate(!pressure$outlier, by = list(sta_id = pressure$sta_id), 
FUN = sum)
9.
..stacktraceon..({
suppressMessages({
library(BiocManager)
options(repos = BiocManager::repositories()) ...
8.
eval(exprs, envir)
7.
eval(exprs, envir)
6.
sourceUTF8(basename(globalPath), envir = globalrenv)
5.
force(code)
4.
withr::with_dir(appDir, {
sourceUTF8(basename(globalPath), envir = globalrenv)
})
3.
loadSupport(appDir, renv = sharedEnv, globalrenv = globalenv())
2.
appParts$onStart()
1.
shiny::runApp(appDir, launch.browser = getOption("browser"))
```

This is related to the aggregate method argument, which I see is connected to pressure$outlier, which is not a valid argument. This should be pressure$isoutlier, correct?

**Comment by Rafnuss** [comment]
Can you update the package to the lastest version (main branch)? The issue is likely due to https://github.com/Rafnuss/GeoPressureR/issues/40. In theory, geopressureviz should return a warning message warning you that `"pressure$isoutliar is deprecated in favor of pressure$isoutlier. Change your code to be back compatible with futur version.`" but still work (see https://github.com/Rafnuss/GeoPressureR/blob/master/inst/geopressureviz/global.R#L85-L93). If you didn't get that, can you update the repository and let me know which species you have the issue with?

**Comment by grhyne** [comment]
Yes it was already updated after your recent commits last week. I have uninstalled and reinstalled / updated using pacman (pacman::p_load_current_gh(char = 'Rafnuss/GeoPressureR')) which has worked before, and I am still getting the same error. Do you have a better method for updating your packages from Github repos?

**Comment by Rafnuss** [comment]
I looked at it more closely and there was a small mistake corrected with https://github.com/Rafnuss/GeoPressureR/commit/70e032516b72d715b263d0cdceff9d4a65b0bacc.

Hope this solves the problem.

**Comment by grhyne** [comment]
@Rafnuss Yep, that fixed it! Thanks
